INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('001','Acriflavin 0.1% Lotion 30ml','2017-7-17','1.89');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('002','Acriflavin 0.1% Lotion 60ml','2017-7-17','2.61');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('003','Albendazole 200 mg/5 ml Suspension','2023-10-10','9.50');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('004','Albendazole 200 mg Tablet','2023-10-10','8.50');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('005','Alcohol 70% Solution','2023-12-12','21.65');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('006','Ascorbic Acid 100 mg Tablet','2023-11-21','14.30');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('007','Benzoic Acid Compound Ointment ','2023-11-21','5.15');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('008','Benzyl Benzoate 25% Emulsion (Adult)','2023-11-22','11.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('009','Bisacodyl 5 mg Tablet','2023-11-22','6.90');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('010','Bromhexine HCl 4 mg/5 ml Elixir','2023-1-22','1.55');

INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('011','Bromhexine HCl 8 mg Tablet','2023-1-22','6.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('012','Calamine Cream','2023-5-25','5.75');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('013','Calamine Lotion','2023-5-25','7.28');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('014','Calcium Lactate 300 mg Tablet','2023-6-22','15.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('015','Charcoal, Activated 250 mg Tablet','2023-4-22','32.50');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('016','Chloramphenicol 0.5% Eye Drops','2023-3-23','6.30');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('017','Chlortetracycline 1 % Eye Ointment','2023-11-22','3.85');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('018','Chlorhexidine Gluconate 5 % Solution','2023-3-23','56.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('019','Chlorpheniramine Maleate 4 mg Tablet','2023-5-25','');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('020','Crotamiton Cream 10%','2023-6-22','');

INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('021','Dexchlorpheniramine Maleate 2 mg/5 ml Syrup','2023-5-25','3.45');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('022','Dextrose 5% Injection 100ml','2023-6-26','2.78');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('023','Dextrose 5% Injection 250ml','2023-6-26','2.60');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('024','Dextrose 5% Injection 500ml','2023-6-26','2.64');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('025','Diphenhydramine Hydrochloride 14 mg/5 ml Expectorant','2023-7-7','6.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('026','Folic Acid 5 mg Tablet','2023-11-22','8.12');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('027','Glycerin 25% and Sodium Chloride 15% Enema','2023-3-23','18.50');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('028','Hydrocortisone 1% Cream','2023-5-25','12.57');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('029','Hydrogen Peroxide 20 Volume Solution','2023-12-12','35.90');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('030','Hyoscine N-Butylbromide 10 mg Tablet','2023-7-31','79.10');

INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('031','Hypromellose 0.3% Eye Drop','2023-3-23','9.90');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('032','Ipratropium Bromide 0.5mg and Salbutamol 2.5mg Nebuliser solution','2023-11-23','2.50');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('033','Liquid Paraffin','2023-11-22','5.96');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('034','Magnesium Trisilicate Mixture','2023-2-16','3.46');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('035','Magnesium Trisilicate 250mg & Aluminium Hydroxide 120mg Tablet','2023-2-16','6.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('036','Mefenamic Acid 250 mg Capsule','2023-8-26','62.40');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('037','Miconazole Nitrate 2% Cream 10g','2023-5-30','5.52');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('038','Miconazole Nitrate 2% Cream 20g','2023-5-30','8.26');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('039','Nystatin 100,000 Units/ml Suspension','2023-5-30','22.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('040','Oral Rehydration Salt','2023-4-20','30.90');

INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('041','Paracetamol 120 mg/5 ml Syrup','2023-3-23','6.90');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('042','Paracetamol 250 mg/5ml Syrup','2023-3-23','8.50');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('043','Paracetamol 125 mg Suppository','2023-4-1','60.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('044','Paracetamol 500 mg Tablet','2023-2-16','2.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('045','Potassium Citrate BP 1gm/5ml Mixture','2023-4-8','4.28');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('046','Prochlorperazine Maleate 5 mg Tablet','2023-8-22','72.60');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('047','	Prolase 10,000 U Tablet','2023-8-22','244.40');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('048','Salbutamol 0.5 % Inhalation Solution','2023-3-30','13.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('049','Silver Sulphadiazine 1 % Cream','2023-3-23','22.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('050','Sodium Chloride 0.45% & Dextrose 5% Injection 250ml','2023-9-3','2.99');

INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('051','Sodium Chloride 0.45% & Dextrose 5% Injection 500ml','2023-9-3','2.90');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('052','Sodium Chloride 0.9% & Dextrose 5% Injection','2023-9-3','6.90');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('053','Sodium Chloride 0.9% Injection 100ml','2023-9-9','2.28');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('054','Sodium Chloride 0.9% Injection 250ml','2023-9-9','2.19');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('055','Vitamin B Complex Tablet','2023-5-22','27.30');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('056','Water for Injection (100ml)','2023-11-25','4.25');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('057','Water for Injection (500ml)','2023-11-25','5.20');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('058','Zinc Oxide, Benzyl Benzoate and Balsam Peru Suppository','2023-3-28','11.00');
INSERT INTO medicine(medicine_ID, Name, Exp_Date, Price)
VALUES ('059','Zink Oxide Cream','2023-7-8','7.80');


