
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('052', 'Gout Check Up', '13.20');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('053', 'Hand Theraphy', '22.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('054', 'Headache Check Up', '11.40');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('055', 'Heart Check Up', '15.50');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('056', 'Heartburn Treatment', '13.20');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('057', 'Heavy Periods Relieve', '11.40');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('058', 'Hiccups Check Up', '11.40');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('059', 'High Blood Pressure Treatment', '21.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('060', 'High Cholesterol Treatment', '21.50');

INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('061', 'Hip Pain Check Up', '13.40');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('062', 'Hormone Test', '34.50');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('063', 'Hyperhidrosis Check Up', '21.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('064', 'Indigestion Treatment', '20.60');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('065', 'Iron, Vitamin and Mineral Level Tests', '31.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('066', 'Irregular Periods Check Up', '24.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('067', 'Irritated and Dry Skin Check Up', '23.50');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('068', 'Itchy Skin Treatment', '26.70');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('069', 'Kidney Stones Scan', '34.50');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('070', 'Knee Pain Check Up', '23.50');

INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('071', 'Leukaemia Check Up', '100.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('072', 'Liver and Kidney Test', '121.10');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('073', 'Lyme Disease', '22.50');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('074', 'Migraines Treatment', '18.90');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('075', 'Nausea', '11.40');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('076', 'Neck Lumps Check Up', '24.90');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('077', 'Neuralgia (Nerve Pain) Treatment', '131.10');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('078', 'Nutrition Consultation', '30.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('079', 'Obesity Check Up', '18.80');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('080', 'Osteoarthiritis Check Up', '18.80');

INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('081', 'Pain When Urinating Check Up', '18.80');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('082', 'Patch Test', '62.50');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('083', 'Physiotherapy', '55.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('084', 'Polycystic Ovary Syndrome Check Up', '142.30');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('085', 'Pregnancy Test', '14.20');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('086', 'Premenstrual Syndrome Check Up', '21.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('087', 'Psoriasis Treatment', '30.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('088', 'Respiratory Check Up', '30.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('089', 'Rotator Cuff Injury', '61.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('090', 'Scoliosis Check Up', '45.40');

INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('091', 'Shoulder Pain Check Up', '30.20');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('092', 'Swollen Check Up', '15.60');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('093', 'Tendonitis Check Up', '25.95');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('094', 'Thyroid Test', '31.20');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('095', 'Tonsil Check Up', '21.10');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('096', 'Ultrasound Scan', '110.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('097', 'Vertigo Check Up', '25.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('098', 'Verruca Treatment', '20.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('099', 'Vomiting Check Up', '19.00');
INSERT INTO treatment (Treatment_ID, Treat_Name, price)
VALUES ('100', 'X-ray', '150.50');



